include ../Makefile.common

OUTPUT_D =../../build/cpp
SOLVER = $(OUTPUT_D)/SwappingParenthesesSolver
COMPILER = g++ -std=gnu++0x -I$(GETTC_HOME)/include/cpp

$(SOLVER): SwappingParenthesesSolver.cpp SwappingParentheses.cpp
	$(COMPILER) -o $(SOLVER) $<

main: setup $(SOLVER)
